version: '3.8'

services:
  ai-assistant:
    image: charanwork/ai-assistant:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"  # Frontend
      - "5000:5000"  # Backend
    volumes:
      # Mount for persistent data (optional)
      - ./sequential_memory:/app/sequential_memory:rw
      - ./.spotify_cache:/app/.spotify_cache:rw
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: ai-assistant-app

networks:
  default:
    driver: bridge