services:
  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: production
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
    volumes:
      - ./sequential_memory:/app/sequential_memory:rw
      - ./.spotify_cache:/app/.spotify_cache:rw
    networks:
      - ai-assistant-network
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - ai-assistant-network
    restart: unless-stopped

networks:
  ai-assistant-network:
    driver: bridge

volumes:
  sequential_memory:
  spotify_cache:
